const recipeOrderByOptions = {
    LESS_MINUTES: "LESS_MINUTES",
    MOST_MINUTES:"MOST_MINUTES",
    LESS_CALORIES: "LESS_CALORIES",
    MOST_CALORIES: "MOST_CALORIES",
    LESS_SUGAR: "LESS_SUGAR",
    MOST_SUGAR: "MOST_SUGAR",
    LESS_PROTEIN:"LESS_PROTEIN",
    MOST_PROTEIN:"MOST_PROTEIN",
    MOST_CARBOHYDRATES:"MOST_CARBOHYDRATES",
    LESS_CARBOHYDRATES:"LESS_CARBOHYDRATES",
}


Object.freeze(recipeOrderByOptions);

module.exports = recipeOrderByOptions;
